baseurl = ""
metaDataFormat = "yaml"
title = "Rohit Kumar Ankam"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false
# [languages]
#   [languages.en]
#     contentDir = "content/en" #English
#     weight = 1
#     languageName = "English"
#     [languages.en.params]
#       introTitle = "Hey! I'm Katheryn Fox"
#       introSubtitle = "26 y/o junior developer who enjoys social card games, blogging and painting"
#       introPhoto = "/picture.jpg"
#     [[languages.en.menu.main]]
#         name = "Blog"
#         url = "blog"
#         weight = 1

#     [[languages.en.menu.main]]
#         name = "About"
#         url = "page/about/"
#         weight = 2

#     [[languages.en.menu.main]]
#         name = "Tags"
#         url = "tags"
#         weight = 3

#   [languages.de]
#     contentDir = "content/de" # Deutsch
#     weight = 2
#     languageName = "Deutsch"
#     title = "Blist (mehrsprachig)"
#     description = "Modernes Blog-Theme für Ihre Hugo-Site."
#     [languages.de.params]
#       introTitle = "Hallo, ich bin Katheryn Fox"
#       introSubtitle = "26-jährige Junior-Entwicklerin, die Spaß an sozialen Kartenspielen, Bloggen und Malen hat"
#       introPhoto = "/picture.jpg"
#     [[languages.de.menu.main]]
#         name = "Blog"
#         url = "blog"
#         weight = 1

#     [[languages.de.menu.main]]
#         name = "Über mich"
#         url = "page/about/"
#         weight = 2

#     [[languages.de.menu.main]]
#         name = "Tags"
#         url = "tags"
#         weight = 3

#   [languages.dy]
#     contentDir = "content/dy" #Example language
#     weight = 3
#     languageName = "Test Language"

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  colormode = "dark"
  
  # Enable search in header
  enableSearch = true
  introTitle = "Hey! I'm Rohit Kumar"
  introSubtitle = "17 y/o CyberSecurity Enthusiast who likes playing with tech."
  description = "Rohit Kumar is a 17 y/o CyberSecurity Enthusiast who likes playing with tech."
  introPhoto = "/profile4.3.webp"
  images = ["screenshot.jpeg"]
  # Custom copyright - optional
  copyright = "Copyright © 2021 - Rohit Kumar Ankam · All rights reserved"
  favicon = "/favicon.ico"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "to know about projects I am working on."
  twitter = "https://twitter.com/rohitkumarankam"
  linkedin = "https://linkedin.com/in/rohitkumarankam"
  github = "https://github.com/rohitkumarankam"
  # medium = "https://medium.com/"
  # reddit = "https://reddit.com/"
  # dribbble = "https://dribbble.com/"

[[menu.main]]
  name = "Contact Me"
  url = "/contact"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
